packages:
  - src
  - webview/main

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - lmdb
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - sharp

overrides:
  '@huggingface/transformers>onnxruntime-node': '1.24.3'
  '@shenghuabi/knowledge>pdfjs-dist': '5.4.624'

minimumReleaseAge: 0

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  electron: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
