import { EditorThemeClasses } from 'lexical';
const CardTheme = {
  hr: 'hr',
  image: 'image',
  link: 'link',
  paragraph: 'p',
  quote: 'blockquote',
  table: 'table',
  tableCell: 'tc',
  tableCellHeader: 'th',
  tableRow: 'tr',
  tableAddColumns: 'tableAddColumns',
  tableAddRows: 'tableAddRows',
  code: 'code',
  characterLimit: 'characterLimit',
  ltr: 'ltr',
  rtl: 'rtl',
  text: {
    bold: 'text-bold',
    code: 'text-code',
    italic: 'text-italic',
    subscript: 'text-subscript',
    superscript: 'text-superscript',
    underline: 'text-underline',
    strikethrough: 'text-strikethrough',
    underlineStrikethrough: 'text-underlineStrikethrough',
  },
  heading: { h1: 'h1', h2: 'h2', h3: 'h3', h4: 'h4', h5: 'h5', h6: 'h6' },
  list: {
    ul: 'ul',
    ol: 'ol',
    checklist: 'cl',
    listitem: 'li',
    listitemChecked: 'liChecked',
    listitemUnchecked: 'liUnChecked',
    nested: { listitem: 'nestedLi' },
    olDepth: ['ol1', 'ol2', 'ol3', 'ol4', 'ol5'],
  },
};
export const ThemeDefine: EditorThemeClasses = {
  ...CardTheme,
  autocomplete: 'PlaygroundEditorTheme__autocomplete',
  blockCursor: 'PlaygroundEditorTheme__blockCursor',
  codeHighlight: {
    atrule: 'tokenAttr',
    attr: 'tokenAttr',
    boolean: 'tokenProperty',
    builtin: 'tokenSelector',
    cdata: 'tokenComment',
    char: 'tokenSelector',
    class: 'tokenFunction',
    'class-name': 'tokenFunction',
    comment: 'tokenComment',
    constant: 'tokenProperty',
    deleted: 'tokenProperty',
    doctype: 'tokenComment',
    entity: 'tokenOperator',
    function: 'tokenFunction',
    important: 'tokenVariable',
    inserted: 'tokenSelector',
    keyword: 'tokenAttr',
    namespace: 'tokenVariable',
    number: 'tokenProperty',
    operator: 'tokenOperator',
    prolog: 'tokenComment',
    property: 'tokenProperty',
    punctuation: 'tokenPunctuation',
    regex: 'tokenVariable',
    selector: 'tokenSelector',
    string: 'tokenSelector',
    symbol: 'tokenProperty',
    tag: 'tokenProperty',
    url: 'tokenOperator',
    variable: 'tokenVariable',
  },
  embedBlock: {
    base: 'PlaygroundEditorTheme__embedBlock',
    focus: 'PlaygroundEditorTheme__embedBlockFocus',
  },
  hashtag: 'PlaygroundEditorTheme__hashtag',

  indent: 'PlaygroundEditorTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'PlaygroundEditorTheme__layoutContainer',
  layoutItem: 'PlaygroundEditorTheme__layoutItem',

  mark: 'PlaygroundEditorTheme__mark',
  markOverlap: 'PlaygroundEditorTheme__markOverlap',

  tableCellActionButton: 'PlaygroundEditorTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'PlaygroundEditorTheme__tableCellActionButtonContainer',
  tableCellEditing: 'PlaygroundEditorTheme__tableCellEditing',
  tableCellPrimarySelected: 'PlaygroundEditorTheme__tableCellPrimarySelected',
  tableCellResizer: 'PlaygroundEditorTheme__tableCellResizer',
  tableCellSelected: 'PlaygroundEditorTheme__tableCellSelected',
  tableCellSortedIndicator: 'PlaygroundEditorTheme__tableCellSortedIndicator',
  tableResizeRuler: 'PlaygroundEditorTheme__tableCellResizeRuler',
  tableSelected: 'PlaygroundEditorTheme__tableSelected',
  tableSelection: 'PlaygroundEditorTheme__tableSelection',
};
